Feature/totp
wedevBr/bankly-laravel pull request #169
Opened 2023-07-24 17:01 UTC by mic-oliveira

Create, Verify and tests TOTP

2023-07-24 21:57 UTC, adeildo-jr requested changes

2023-07-24 21:57 UTC, adeildo-jr commented on tests/BanklyTOTPTest.php
> +        $addressingKey->value = '+5522992075623';
Remove personal data

2023-07-24 21:57 UTC, adeildo-jr commented on tests/TOTP/TOTPValidatorTest.php
> +        $addressingKey->value = "+5511987654321";
Remove personal data, use faker instead

2023-07-25 00:57 UTC, mic-oliveira commented on tests/TOTP/TOTPValidatorTest.php
> +        $addressingKey->value = "+5511987654321";
changed to faker numerify

2023-07-25 05:05 UTC, merged